### Criar Usuário
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Slim Doe",
  "email": "john.doe@teste1.com",
  "password": "securepassword"
}

### Variavel de senha
@password = "securepassword"

### Login do Usuário
# @name login
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "email": "john.doe@teste1.com",
  "password": {{password}}
}

###
@tokenLogin = {{login.response.body.token}}

### Buscar dados do usuário com autenticado
GET http://localhost:3333/profile
Authorization: Bearer {{tokenLogin}}

### Recuperar senha
# @name resetPassword
POST http://localhost:3333/password-recover
Content-Type: application/json

{
  "email": "john.doe@teste.com"
}

###
@tokenReset = {{resetPassword.response.body.recoveryToken}}

### Resetar Senha
POST http://localhost:3333/password-reset
Content-Type: application/json

{
  "token": "{{tokenReset}}",
  "password": "newpassword"
}

### Criar Organização
POST http://localhost:3333/organizations
Content-Type: application/json
Authorization: Bearer {{tokenLogin}}

{
  "name": "Organization Test",
  "domain": "test1.com",
  "shouldAttachUsersByDomain": true
}

### Buscar Organizações
GET http://localhost:3333/organizations
Authorization: Bearer {{tokenLogin}}


### Buscar Membros da Organização
GET http://localhost:3333/organization/organization-test/membership
Authorization: Bearer {{tokenLogin}}

### Shutdown Organização
DELETE http://localhost:3333/organizations/organization-test
Authorization: Bearer {{tokenLogin}}

